name = "LoSSETT"
uuid = "bf3948c2-06a1-43a7-8642-36c654ef2c69"
authors = ["LoSSETT contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
